"""baseline: schema completo + dominio de custo

Revision ID: 60d426c744b0
Revises: 
Create Date: 2026-09-23 12:27:37.589291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60d426c744b0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agricultural_supplies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('FERTILIZER', 'CORRECTIVE', 'PESTICIDE', 'FUEL', name='supplycategory'), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seasons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('farms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('producer_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('total_area_ha', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['producer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('INCOME', 'EXPENSE', name='transactiontype'), nullable=False),
    sa.Column('category', sa.Enum('SUPPLY', 'LABOR', 'COFFEE_SALE', 'MAINTENANCE', name='transactioncategory'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PAID', 'PENDING', name='transactionstatus'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('machines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hourly_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('area_ha', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('variety', sa.String(length=100), nullable=True),
    sa.Column('planting_year', sa.Integer(), nullable=True),
    sa.Column('altitude_m', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('status', sa.Enum('IN_PRODUCTION', 'RENOVATION', 'DEVELOPMENT', name='plotstatus'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_definitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit_description', sa.String(length=255), nullable=True),
    sa.Column('unit_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('temperature_celsius', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('precipitation_mm', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('relative_humidity', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('REGISTERED', 'THIRD_PARTY', name='workertype'), nullable=False),
    sa.Column('daily_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('harvest_estimates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plot_id', sa.String(length=36), nullable=False),
    sa.Column('season', sa.String(length=20), nullable=False),
    sa.Column('estimated_sacks', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estimated_yield_per_ha', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plot_varieties',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plot_id', sa.String(length=36), nullable=False),
    sa.Column('variety', sa.String(length=100), nullable=False),
    sa.Column('planting_year', sa.Integer(), nullable=True),
    sa.Column('area_ha', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plot_id', sa.String(length=36), nullable=False),
    sa.Column('season_id', sa.String(length=36), nullable=False),
    sa.Column('sacks_produced', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('harvest_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plot_id', 'season_id', name='uq_production_plot_season')
    )
    op.create_table('soil_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plot_id', sa.String(length=36), nullable=False),
    sa.Column('collection_date', sa.Date(), nullable=False),
    sa.Column('ph', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('organic_matter', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('report_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plot_id', sa.String(length=36), nullable=True),
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('alert_type', sa.Enum('WEATHER', 'AGRONOMIC', 'SYSTEM', name='alerttype'), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technical_recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agronomist_id', sa.String(length=36), nullable=False),
    sa.Column('plot_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', name='recommendationstatus'), nullable=False),
    sa.ForeignKeyConstraint(['agronomist_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traceability_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plot_id', sa.String(length=36), nullable=False),
    sa.Column('harvest_season', sa.String(length=20), nullable=False),
    sa.Column('batch_code', sa.String(length=100), nullable=False),
    sa.Column('coffee_type', sa.Enum('NATURAL', 'PULPED_NATURAL', name='coffeetype'), nullable=False),
    sa.Column('harvest_date', sa.Date(), nullable=False),
    sa.Column('total_volume_measures', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cupping_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('quality_classification', sa.String(length=100), nullable=True),
    sa.Column('cupping_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_code')
    )
    op.create_table('agricultural_activities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plot_id', sa.String(length=36), nullable=False),
    sa.Column('season_id', sa.String(length=36), nullable=True),
    sa.Column('recommendation_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.Enum('FERTILIZATION', 'PRUNING', 'HARVEST', 'IRRIGATION', 'PESTICIDE_APPLICATION', name='activitytype'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', name='activitystatus'), nullable=False),
    sa.Column('worked_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('labor_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['technical_recommendations.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coffee_trackings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tracking_code', sa.String(length=20), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('current_stage', sa.Enum('COLHEITA', 'LAVADOR', 'TERREIRO', 'SECADOR', 'TULHA', 'BENEFICIAMENTO', 'CLASSIFICACAO', 'COMERCIALIZACAO', 'FINALIZADO', name='trackingstage'), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', name='trackingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['traceability_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tracking_code')
    )
    op.create_table('dryer_phases',
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('equipment_identification', sa.String(length=100), nullable=True),
    sa.Column('drying_date', sa.Date(), nullable=False),
    sa.Column('usage_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('final_humidity', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['traceability_batches.id'], ),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_table('patio_phases',
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('exposure_days', sa.Integer(), nullable=True),
    sa.Column('exit_humidity', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['traceability_batches.id'], ),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_table('processing_phases',
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('processing_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('beverage_classification', sa.String(length=100), nullable=True),
    sa.Column('bc_weight_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('escolha_weight_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fundo_weight_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['traceability_batches.id'], ),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_table('sales',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('shipment_invoice', sa.String(length=100), nullable=True),
    sa.Column('destination_warehouse', sa.String(length=255), nullable=True),
    sa.Column('sale_invoice', sa.String(length=100), nullable=True),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('customer', sa.String(length=255), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['traceability_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id')
    )
    op.create_table('silo_phases',
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('silo_identification', sa.String(length=100), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('storage_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['traceability_batches.id'], ),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_table('washer_phases',
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('processing_date', sa.Date(), nullable=False),
    sa.Column('separated_measures', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['traceability_batches.id'], ),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_table('activity_supplies',
    sa.Column('activity_id', sa.String(length=36), nullable=False),
    sa.Column('supply_id', sa.String(length=36), nullable=False),
    sa.Column('applied_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['agricultural_activities.id'], ),
    sa.ForeignKeyConstraint(['supply_id'], ['agricultural_supplies.id'], ),
    sa.PrimaryKeyConstraint('activity_id', 'supply_id'),
    # UniqueConstraint removida: PK composta já garante unicidade; Oracle ORA-02261
    # rejeita constraint duplicada sobre as mesmas colunas.
    )
    op.create_table('labor_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('activity_id', sa.String(length=36), nullable=False),
    sa.Column('labor_type', sa.Enum('DIARIA', 'SERVICO', name='labortype'), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=True),
    sa.Column('service_definition_id', sa.String(length=36), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['agricultural_activities.id'], ),
    sa.ForeignKeyConstraint(['service_definition_id'], ['service_definitions.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('machine_usages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('activity_id', sa.String(length=36), nullable=False),
    sa.Column('machine_id', sa.String(length=36), nullable=False),
    sa.Column('hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['agricultural_activities.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracking_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tracking_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.Enum('COLHEITA', 'LAVADOR', 'TERREIRO', 'SECADOR', 'TULHA', 'BENEFICIAMENTO', 'CLASSIFICACAO', 'COMERCIALIZACAO', 'FINALIZADO', name='trackingstage'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.String(length=255), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tracking_id'], ['coffee_trackings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracking_events')
    op.drop_table('machine_usages')
    op.drop_table('labor_entries')
    op.drop_table('activity_supplies')
    op.drop_table('washer_phases')
    op.drop_table('silo_phases')
    op.drop_table('sales')
    op.drop_table('processing_phases')
    op.drop_table('patio_phases')
    op.drop_table('dryer_phases')
    op.drop_table('coffee_trackings')
    op.drop_table('agricultural_activities')
    op.drop_table('traceability_batches')
    op.drop_table('technical_recommendations')
    op.drop_table('system_alerts')
    op.drop_table('soil_analyses')
    op.drop_table('productions')
    op.drop_table('plot_varieties')
    op.drop_table('harvest_estimates')
    op.drop_table('workers')
    op.drop_table('weather_logs')
    op.drop_table('service_definitions')
    op.drop_table('plots')
    op.drop_table('machines')
    op.drop_table('financial_transactions')
    op.drop_table('farms')
    op.drop_table('users')
    op.drop_table('seasons')
    op.drop_table('agricultural_supplies')
    # ### end Alembic commands ###
